language: go

sudo: false

go:
  - "1.12"
  - tip

env:
  - GO111MODULE=on

install: true

before_script:
  - go get ./...
  - go vet ./...

script:
  - go build
  - go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic
after_script:
  - bash <(curl -s https://codecov.io/bash)
