name: Publish Docker image to GitHub Package Registry
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Files
      uses: actions/checkout@v2
    - name: Set tag
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build image
      run: docker build -f Dockerfile --no-cache -t "docker.pkg.github.com/$GITHUB_REPOSITORY:latest" .
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - name: Publish latest to GPR
      run: docker tag pubsub docker.pkg.github.com/$GITHUB_REPOSITORY:latest
    - name: Publish tag to GPR
      run: |
        docker tag pubsub docker.pkg.github.com/$GITHUB_REPOSITORY:${{ steps.vars.outputs.tag }}
        echo "Created tag ${{ steps.vars.outputs.tag }}"
