name: Publish Docker image to GitHub Package Registry
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Files
      uses: actions/checkout@v2
    - name: Set tag
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build image
      run: |
        echo "docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}"
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
        echo "Created tag ${{ steps.vars.outputs.tag }}"
    - name: Publish image
      run: |
        echo "docker tag pubsub docker.pkg.github.com/$GITHUB_REPOSITORY:latest"
        docker tag pubsub docker.pkg.github.com/$GITHUB_REPOSITORY:latest
        echo "docker tag pubsub docker.pkg.github.com/$GITHUB_REPOSITORY:${{ steps.vars.outputs.tag }}"
        docker tag pubsub docker.pkg.github.com/$GITHUB_REPOSITORY:${{ steps.vars.outputs.tag }}
